### ISSUE TITLE
[Question] Which STL file should I 3D print?

### ISSUE THREAD

**Issue by hrpnx** [Lenrul/beymod#1]
I'm planning to create a Mounting Attachment for IPD 72 mm. Could I ask two questions?

1) Among the files uploaded to the repository, which STL file should I 3D print? Please provide a list.
2) This will be my first time 3D printing, so I'm unsure which material to use (ABS, PLA, PP, etc). Could you advise me?

Thank you.

**Comment by Lenrul** [comment]
Just note that I have not worked on getting eye tracking beyond 66-72 ipd, you'd be the first to do so, and this serves more as a guide to set yours up specifically to your needs.

you are going to need this printed:
[Eye Tube Camera Attachments](https://github.com/Lenrul/beymod/tree/main/66-72) in ABS/ASA
[esp32 / USB hub / V4 Prohurtz IR Board base](https://github.com/Lenrul/beymod/blob/main/Beymodv5.stl) in ABS/ASA
[Board Holder](https://github.com/Lenrul/beymod/blob/main/Beymod%20Cover%20Top.stl) Any Material

it uses Prohurtz v4 hub [here](https://store.eyetrackvr.dev/products/v4-mini-fully-solderless-kit)
if you want to build with the usb hub, here's this AliExpress [link](https://www.aliexpress.us/item/3256804070458646.html?spm=a2g0o.order_list.order_list_main.159.69821802v8KOY4&gatewayAdapt=glo2usa)

and since this is your first time 3d printing, id recommend doing a bit of research on filament temps qualities/ disadvantages as abs/asa is quite hard to handle without an enclosure. but for a beginner, use pla for now until you get familiarized with the warping issues that abs/asa will give you.

if the hint of getting that aliexpress usb hub didnt get you, you will also need soldering iron for this as well unless you are using an external hub. but that's on you.

**Comment by hrpnx** [comment]
Thank you so much for your detailed response! I'll try it.
